block_localization: 
    odom_child_frame_id: "livox_frame"

    # lidar settings
    lidarTopic: "/livox/points"
    have_ring_time_channel: false     # if "XYZI", false; if "XYZIRT", true
    lidarMinRange: 2.0
    lidarMaxRange: 80
    
    # imu settings
    imuTopic: "/livox/imu"
    imuAccNoise: 0.7
    imuGyrNoise: 0.7
    gravity: 0.9
    imuFrequency: 150 # given as 200

    # sensors extrinsics T_lb actually between LiDAR & IMU, only extrinsicRot is used in code
    extrinsicTrans: [0, 0, 0]
    extrinsicRot: [1, 0, 0,
                   0, 1, 0,
                   0, 0, 1]
    extrinsicRPY: [1, 0, 0,
                   0, 1, 0,
                   0, 0, 1]

    # only one in use
    # extrinsicRot: [  0.001496, -1.001448, -0.001148,
    #                 0.098952, -0.002304, 0.996552,
    #                 -0.996548, -0.003048, 0.097496 ]

    L2gt_t: [ 0, 0, 0 ]
    L2gt_R: [ 1, 0, 0,
              0, 1, 0,
              0, 0, 1 ]

    # system settings
    cool_time_duration: 5    # during "cool_time", imu inputs are ignored
    key_interval: 0.1           # select key frames according to time interval
    mapqry_interval: 1.0        # query time to change BM
    
    # ndt settings
    ndt_neighbor_search_method: "DIRECT7"
    ndt_resolution: 1
    ndt_epsilon: 0.001           # maximum allowable translation squared difference between two consecutive transformations
    penalty_thres: 1
    penalty_weight: 5

    # gtsam settings
    odomLinearNoise: 0.7
    odomAngularNoise: 1
    active_factors: 70
    preserve_factors: 30

    # initialpose settings
    # if "specify_init_pose" is true, pose estimator will be initialized with the following params. Otherwise, you need to input an initial pose with "2D Pose Estimate" on rviz" 
    specify_init_pose: true
    init_pos_x: -86.040205
    init_pos_y: -8.857126
    init_pos_z: -11.043077
    init_ori_w: 0.754584
    init_ori_x: -0.011549
    init_ori_y: -0.014147
    init_ori_z: -0.655949


globalmap_server:
    globalmap_dir: "/home/wuxiao/Desktop/GLIL_Dataset/block_maps_hard/" # directory address of your BMs; end with "/"
    downsample_resolution: 0.3
    
